#!/bin/bash -v

# This script runs on all instances
# It installs a salt minion

# The pnda_env-<cluster_name>.sh script generated by the CLI should
# be run prior to running this script to define various environment
# variables

set -e

/tmp/package-install.sh

yum -y install xfsprogs wget salt-minion-2015.8.11-1.el7 curl
#enable boot time startup
systemctl enable salt-minion.service

# Set the master address the minion will register itself with
cat > /etc/salt/minion <<EOF
master: $PNDA_SALTMASTER_IP
EOF

# Set the grains common to all minions
cat >> /etc/salt/grains <<EOF
pnda:
  flavor: $PNDA_FLAVOR
  is_new_node: True
hadoop.distro: '$HADOOP_DISTRO'

pnda_cluster: $PNDA_CLUSTER
EOF

if [ -d "/etc/cloud" ]; then
cat >> /etc/cloud/cloud.cfg <<EOF
preserve_hostname: true
EOF
fi

/tmp/volume-mappings.sh /etc/pnda/disk-config/requested-volumes /etc/pnda/disk-config/volume-mappings