#!/bin/bash -v

# This script runs on all instances
# - sets the minion ID
# - sets the hostname
# - installs the minion keys and restarts the minion

# The pnda_env-<cluster_name>.sh script generated by the CLI should
# be run prior to running this script to define various environment
# variables

set -e

if [ "x$LDAP_SERVER" != "x" ]; then
  # Install and configure LDAP
  # This code needs to run before the minion is started!
  yum install -y nss-pam-ldapd openldap-clients
  authconfig --enableldap --enableldapauth --ldapserver=$LDAP_SERVER --ldapbasedn="dc=$LDAP_BASE_DN" --enablemkhomedir --update
fi

# The minion_id file is placed onto the minion by saltmaster-gen-keys.sh
# along with the minion.pem and minion.pub keys that it can use
# to register as a minion with that specific ID.
MINION_ID=$(cat minion_id)
cat >> /etc/salt/minion <<EOF
id: $MINION_ID
EOF

echo $MINION_ID > /etc/hostname
hostname $MINION_ID

mkdir -p /etc/salt/pki/minion/

if [ -f minion.pem ]; then
  mv minion.pem /etc/salt/pki/minion/
fi

if [ -f minion.pub ]; then
  mv minion.pub /etc/salt/pki/minion/
fi

service salt-minion restart
