#!/bin/bash -v

# This script runs on all instances
# It installs the minion keys and restarts the minion

# The pnda_env-<cluster_name>.sh script generated by the CLI should
# be run prior to running this script to define various environment
# variables

set -e

mkdir -p /etc/salt/pki/minion/

if [ -f minion.pem ]; then
  mv minion.pem /etc/salt/pki/minion/
fi

if [ -f minion.pub ]; then
  mv minion.pub /etc/salt/pki/minion/
fi

service salt-minion restart