#!/bin/bash -v

# This script runs on instances with a node_type tag of "gateway"
# It sets the roles that determine what software is installed
# on this instance by platform-salt scripts

# The pnda_env-<cluster_name>.sh script generated by the CLI should
# be run prior to running this script to define various environment
# variables

set -e

cat >> /etc/salt/grains <<EOF
roles:
  - knox
EOF
